# Generated by Django 6.0.5 on 2026-05-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_phone_number_ownerprofile_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
    ]
