# Generated by Django 6.0.5 on 2026-05-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='company_id',
            new_name='commercial_reg',
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='join_date',
            new_name='created_at',
        ),
    ]
